Repository Book-Study-For-Developer/Javascript-React-Design-Pattern, pull requests merged in 2025-05, with the labels that each got.

#1 [1주차] 1~6장 내용 정리
  하현준/01. 디자인 패턴 소개/README.md
  하현준/02. 패턴성 검증, 프로토 패턴 그리고 세 가지 법칙/README.md
  하현준/03. 패턴 구조화 및 작성/README.md
  하현준/04. 안티 패턴/README.md
  하현준/05. 최신 자바스크립트 문법과 기능/README.md
  하현준/06. 디자인 패턴의 유형/README.md
Labels: 1회차

#3 docs: 스터디 1회차 1-6장 내용 정리
  안예지/01. 디자인 패턴 소개/README.md
  안예지/02. 패턴성 검증, 프로토 패턴 그리고 세 가지 법칙/README.md
  안예지/03. 패턴 구조화 및 작성/README.md
  안예지/04. 안티 패턴/README.md
  안예지/05. 최신 자바스크립트 문법과 기능/README.md
  안예지/06. 디자인 패턴의 유형/README.md
  안예지/README.md
Labels: 1회차

#2 [1회차] 1, 2, 3, 4, 5, 6장 정리
  박영인/Chapter 01 - 디자인 패턴 소개.md
  박영인/Chapter 02 - 패턴성 검증, 프로토 패턴 그리고 세가지 법칙.md
  박영인/Chapter 03 - 패턴 구조화 및 작성.md
  박영인/Chapter 04 - 안티 패턴.md
  박영인/Chapter 05 - 최신 자바스크립트 문법과 기능.md
  박영인/Chapter 06 - 디자인 패턴의 유형.md
Labels: 1회차

#4 [1주차] 1-6장 내용 정리
  김가은/CH1_디자인 패턴 소개/README.md
  김가은/CH2_패턴성 검증, 프로토 패턴 그리고 세 가지 법칙/README.md
  김가은/CH3_패턴 구조화 및 작성/README.md
  김가은/CH4_안티 패턴/README.md
  김가은/CH5_최신 자바스크립트 문법과 기능/README.md
  김가은/CH6_디자인 패턴의 유형/README.md
Labels: 1회차

#6 [1주차] 1~6장 내용 정리
  김효리/01. 디자인 패턴 소개/README.md
  김효리/02. 패턴성 검증, 프로토 패턴 그리고 세 가지 법칙/README.md
  김효리/03. 패턴 구조화 및 작성/README.md
  김효리/04. 안티 패턴/README.md
  김효리/05. 최신 자바스크립트 문법과 기능/README.md
  김효리/06. 디자인 패턴의 유형/README.md
Labels: 1회차

#5 [1주차] 1~6장 내용 정리
  김보경/01_디자인_패턴_소개/README.md
  김보경/02_패턴성_검증,_프로토_패턴_그리고_세_가지_법칙/README.md
  김보경/03_디자인_패턴의_구조/README.md
  김보경/04_안티패턴/README.md
  김보경/05_최신_자바스크립트_문법과_기능/README.md
  김보경/06_디자인_패턴의_유형/README.md
Labels: 1회차

#7 [2회차] 7장 내용 정리
  하현준/07. 자바스크립트 디자인 패턴/01_README.md
Labels: 2회차

#12 [2주차] 7장(~ 플라이웨이트 패턴) 내용 정리
  김보경/01_디자인_패턴_소개/README.md
  김보경/07_자바스크립트_디자인_패턴/01_README.md
Labels: 2회차

#9 docs: ch07 - 자바스크립트 디자인 패턴 내용 정리
  안예지/07. 자바스크립트 디자인패턴/README.md
  안예지/README.md
Labels: 2회차

#11 [2주차] 7장 (생성 패턴, 구조 패턴) 내용 정리
  김가은/CH7_자바스크립트 디자인 패턴/README.md
Labels: 2회차

#10 [2회차] 7장 내용 정리
  김효리/07. 자바스크립트 디자인 패턴/README.md
Labels: 2회차

#8 [2회차] 7장 내용 정리
  박영인/Chapter 07 - 자바스크립트 디자인 패턴.md
Labels: 2회차

#14 docs: 7장 행위패턴/8장 내용 정리
  안예지/07. 자바스크립트 디자인패턴/README_NEW.md
  안예지/08. 자바스크립트 MV*패턴/README.md
  안예지/README.md
Labels: 3회차

#13 [3회차] 7장, 8장 내용 정리
  하현준/07. 자바스크립트 디자인 패턴/02_README.md
  하현준/08. 자바스크립트 MV* 패턴/README.md
Labels: 3회차

#17 [3주차] 7장 (행위 패턴), 8장 내용 정리
  김효리/07. 자바스크립트 디자인 패턴/README.md
  김효리/08. 자바스크립트 MV_ 패턴/README.md
Labels: 3회차

#16 [3회차] 7장(행위패턴), 8장 내용 정리
  박영인/Chapter 07 - 자바스크립트 디자인 패턴.md
  박영인/Chapter 08 - 자바스크립트 MV* 패턴.md
Labels: 3회차

#20 [4주차] 9장, 10장 내용 정리
  김보경/09_비동기_프로그래밍_패턴/README.md
  김보경/10_모듈형_자바스크립트_디자인_패턴/README.md
Labels: 4회차

#21 [4주차] 9장, 10장 내용 정리
  하현준/09. 비동기 프로그래밍 패턴/README.md
Labels: 4회차
